services:
    app:
        image: app:test
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0.27
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app_db
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
