#!/usr/bin/with-contenv sh

# Enable opcache for production
if [ "$APP_ENV" == "production" ]; then
    echo "Production"
    # TODO insert optimize commands?
else
    echo "Development"
fi

# Enable xdebug if XDEBUG_ENABLE=true
if [ "$XDEBUG_ENABLE" == "true" ]; then
    if [ -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.disabled ]; then
        echo "Enabling PHP-FPM's xdebug"
        mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.disabled /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    else
        echo "Xdebug is not installed on the container"
    fi
else
    echo "Xdebug not enabled"
fi

exec /usr/local/sbin/php-fpm --nodaemonize
